[build]
  publish = "blog-dist"
  command = "pip install -r requirements.txt && npm run build"

[[redirects]]
from = "/tag/:tag"
to = "/tag/:tag/index.html"
status = 200
force = true

[[redirects]]
from = "/page/:page"
to = "/page/:page/index.html"
status = 200
force = true

[[redirects]]
  from = "/blog/:slug"
  to = "/:slug.html"
  status = 200

[[redirects]]
  from = "/:slug"
  to = "/:slug.html"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
