"""Purpose-built content and layouts for the five primary navigation destinations."""
from pathlib import Path
from html import escape as E
from bs4 import BeautifulSoup
BOOK='https://media.listerpros.com/order-forms/ad92f54b-433c-4a6a-8be9-f9a9e9d2d97e'
ROOT=Path(__file__).resolve().parent
PAGES={'why.html','pricing.html','portfolio.html','teams.html','resources.html'}
def soup(text):return BeautifulSoup(text,'html.parser')
def img(name,alt,cls='',eager=False):return f'<img class="{cls}" src="/images/{name}" alt="{E(alt)}" width="1200" height="800" '+('fetchpriority="high"' if eager else 'loading="lazy"')+'>'
def button(text,href=BOOK,secondary=False):return f'<a class="mp-button{" mp-outline" if secondary else ""}" href="{href}">{text} <span aria-hidden="true">↗</span></a>'
def eyebrow(text):return f'<p class="mp-eyebrow">{text}</p>'
def closing(title,body,primary='Book your next shoot',href=BOOK):return f'<section class="mp-close"><div class="mp-wrap"><div>{eyebrow("ListerPros · Arizona since 2013")}<h2>{title}</h2><p>{body}</p></div><div class="mp-actions">{button(primary,href)}{button("Talk to our team","tel:4805827767",True)}</div></div></section>'
def quote(text,name,company):return f'<figure class="mp-quote"><div class="mp-stars" aria-label="5 stars">★★★★★</div><blockquote>“{text}”</blockquote><figcaption><strong>{name}</strong><span>{company} · Review excerpt</span></figcaption></figure>'

def why():
 return f'''<section class="mp-hero mp-why-hero"><div class="mp-wrap mp-split"><div>{eyebrow('Why agents choose ListerPros')}<h1>The photos get attention.<br><em>The experience earns<br>your next booking.</em></h1><p class="mp-lead">You may already have a photographer. Give us one listing to show you what our local team, clear communication and care can bring to your business.</p><div class="mp-actions">{button('Try us on one listing')}{button('Explore the work','/portfolio',True)}</div><a class="mp-proof-link" href="/testimonials"><span class="mp-stars">★★★★★</span> 5.0 from 400+ Google reviews ↗</a></div><div class="mp-why-visual">{img('portfolio/interior-1.jpg','Bright kitchen with natural wood cabinetry, photographed by ListerPros','mp-main-image',True)}<div class="mp-person">{img('jarek.jpg','Jarek, a ListerPros photographer')}<div><strong>Local people.<br>A team behind you.</strong><span>Meet Jarek and the Arizona team.</span><a href="/about">Get to know us ↗</a></div></div></div></div></section>
 <section class="mp-proof-strip"><div class="mp-wrap"><p><strong>Since 2013</strong><span>Arizona owned and operated</span></p><p><strong>150K+</strong><span>Listings photographed</span></p><p><strong>5,000+</strong><span>Agents served</span></p><a href="/testimonials">Read their experiences ↗</a></div></section>
 <section class="mp-section"><div class="mp-wrap"><div class="mp-section-heading">{eyebrow('What you are really choosing')}<h2>Good media matters.<br>So does everything around it.</h2><p>From the appointment at your seller’s home to the files you need for launch, the experience should make your job easier.</p></div><div class="mp-experience-grid"><article><span class="mp-number">01</span><h3>People who represent you well.</h3><p>Our Arizona photographers are employees, with branded shirts and a local team behind them. Your sellers meet someone who represents your choice of media partner.</p><a href="/about">Meet the team ↗</a></article><article><span class="mp-number">02</span><h3>Clear choices. Fewer loose ends.</h3><p>Compare packages, choose your services and see available appointments online. Review the final total before you book.</p><a href="/pricing">Find your package ↗</a></article><article><span class="mp-number">03</span><h3>Support after the shoot.</h3><p>Standard photos arrive within five hours of shoot completion. If something needs attention, our team is here to help you work through it.</p><a href="/terms-of-service">Read our Make-It-Right policy ↗</a></article></div></div></section>
 <section class="mp-section mp-soft"><div class="mp-wrap mp-evidence"><div>{eyebrow('The difference, in their words')}<h2>Easy to book.<br>Easy to come back.</h2><p>These are the things agents mention when they talk about working with ListerPros.</p><a class="mp-text-link" href="/testimonials">More agent reviews ↗</a></div><div class="mp-quote-grid">{quote('Super easy to book, great communication','Melissa Bermudez','HomeSmart')}{quote('Easy to schedule and always consistent.','William Brimie','Rio Salado Realty')}{quote('ListerPros has been my go to for almost 9 years!','Brittany Medina','My Home Group')}</div></div></section>
 <section class="mp-section"><div class="mp-wrap mp-split mp-benefit">{img('community/community-012.jpg','Arizona community amenities','mp-benefit-photo')}<div>{eyebrow('More than the property itself')}<h2>Show buyers the neighborhood, too.</h2><p>A pool, a park, a place to spend the weekend. Our archive covers 1,000+ Arizona communities so you can bring more of the lifestyle into your listing.</p><a class="mp-text-link" href="/community-photos/">Find your community ↗</a></div></div></section>
 {closing('You do not have to change everything.<br>Start with one listing.','Compare our work, communication and service with what matters to you. Let the experience earn your next booking.','Book your first ListerPros shoot')}'''

def pricing(source):
 cards=source.select('.pricing-card');names=['Photos Only','Essential','Premier','Elite'];goals=['A polished MLS debut','Photos + a sense of the layout','Video + your personal brand','The complete presentation'];descriptions=['Keep it focused on professional listing photos.','Add a Zillow 3D tour and floor plan to your photos.','Bring the home and your on-camera presence together.','Combine photography, video, drone and Matterport.']
 rendered=[]
 for i,c in enumerate(cards):
  data=' '.join(f'{k}="{E(str(v),quote=True)}"' for k,v in c.attrs.items() if k.startswith('data-'))
  items=[]
  for li in c.select('li'):
   text=li.get_text(' ',strip=True)
   if '20-35' in text:text=E(text).replace('20-35','<span class="photos-display">20–35</span>')
   else:text=E(text)
   items.append('<li>'+text+'</li>')
  rendered.append(f'<article class="mp-package pricing-card" data-package="{i}" {data}><p class="mp-package-goal">{goals[i]}</p><h3>{names[i]}</h3><p class="mp-package-description">{descriptions[i]}</p><p class="mp-package-price"><strong class="price-display">${c["data-price-small"]}</strong><span>/ shoot</span></p><p class="sqft-display">Up to 2,000 sq ft</p><ul>{"".join(items)}</ul>{button("Choose "+names[i])}</article>')
 addon=next(h for h in source.find_all('h2') if 'Carte' in h.text).find_parent('section');groups=[]
 for h in addon.select('h3'):
  box=h.find_parent('div').parent;rows=[]
  for li in box.select('li'):
   spans=li.find_all('span',recursive=False)
   if len(spans)==2:
    label=spans[0].get_text(' ',strip=True);price=spans[1].get_text(' ',strip=True)
    if label=='Community Photos':continue # The archive and the old $50 listing conflict; link to the library separately below.
    rows.append(f'<div><dt>{E(label)}</dt><dd>{E(price)}</dd></div>')
  groups.append(f'<details class="mp-addons"><summary>{E(h.text)}</summary><dl>{"".join(rows)}</dl></details>')
 return f'''<section class="mp-hero mp-price-hero"><div class="mp-wrap"><div class="mp-price-intro"><div>{eyebrow('Pricing that starts with your listing')}<h1>The right media.<br><em>A clear starting price.</em></h1><p class="mp-lead">Choose the property size, compare what’s included, and book the services your listing needs.</p></div><div class="mp-price-note"><strong>Photos from $139</strong><p>For homes up to 2,000 sq ft.</p><span>See your final total and available appointments during booking.</span></div></div></div></section>
 <section class="mp-section mp-package-section" id="packages"><div class="mp-wrap"><div class="mp-choice-bar"><div><label>1. Choose the property size</label><div class="mp-size-control" role="group" aria-label="Property size"><button class="size-btn" data-size="small" aria-pressed="true">Up to 2,000 sq ft</button><button class="size-btn" data-size="medium" aria-pressed="false">2,001–4,000</button><button class="size-btn" data-size="large" aria-pressed="false">4,001+</button></div></div><div><label for="mp-goal">2. What’s your goal?</label><select id="mp-goal"><option value="all">Compare all four packages</option><option value="0">Give my listing professional photos</option><option value="1">Show the layout with a 3D tour and floor plan</option><option value="2">Showcase the home with video and my on-camera intro</option><option value="3">Market the home with photos, video, drone and 3D</option></select></div></div><p class="mp-choice-result" id="mp-choice-result" aria-live="polite">All four packages include professional photography.</p><div class="mp-packages">{''.join(rendered)}</div><p class="mp-fine">Published starting prices. Market, property size and selected services affect your final total. Confirm all inclusions and availability during booking.</p></div></section>
 <section class="mp-included-band"><div class="mp-wrap"><div><strong>Standard photos in 5 hours</strong><p>From shoot completion. Other media have separate delivery times.</p><a href="/help-center#delivery">Delivery details ↗</a></div><div><strong>People you can reach</strong><p>Questions before booking or after delivery? Talk with our team.</p><a href="tel:4805827767">480.582.7767 ↗</a></div><div><strong>A clear next step</strong><p>Select your services, appointment and final total in the order form.</p><a href="{BOOK}">Open booking ↗</a></div></div></section>
 <section class="mp-section mp-soft" id="add-ons"><div class="mp-wrap mp-addon-layout"><div>{eyebrow('Make it fit your listing')}<h2>Start with a package.<br>Add what matters.</h2><p>Aerial context, a social video or an extra set of photos. These services can be selected during booking.</p>{button('Build your shoot')}<p class="mp-fine">Looking for neighborhood amenities? <a href="/community-photos/">Browse the community photo archive.</a></p></div><div>{''.join(groups)}<p class="mp-fine">Combo pricing and final service options are shown in the order form.</p></div></div></section>
 <section class="mp-section"><div class="mp-wrap mp-faq-layout"><div>{eyebrow('Before you choose')}<h2>A few useful answers.</h2></div><div><details class="mp-faq"><summary>Which package should I start with?</summary><p>Choose Photos Only for a photo-focused listing. Essential adds a Zillow 3D tour and floor plan. Premier adds video and an on-camera introduction. Elite brings together a broader photo, video and 3D collection. Compare the listed inclusions above.</p></details><details class="mp-faq"><summary>Can I customize a package?</summary><p>Yes. Explore add-ons above, then select your services in the order form. You can review your total before booking.</p></details><details class="mp-faq"><summary>Does five-hour delivery apply to every service?</summary><p>It applies to standard photography after shoot completion. Video, luxury photography and other services have their own timelines. <a href="/help-center#delivery">See service-specific delivery details.</a></p></details><details class="mp-faq"><summary>Booking for a team or brokerage?</summary><p>Tell us about your agents, listing volume and media needs. <a href="/teams">Explore a team arrangement.</a></p></details></div></div></section>{closing('Your next listing starts here.','Choose your services and find an appointment that fits.','Book your shoot')}'''

def portfolio(source):
 photos=source.select('.portfolio-item');items=[]
 for n,p in enumerate(photos):
  photo=p.img;src='/'+photo['src'].lower();cat=p['data-category'];caption={'interior':'Interior photography','exterior':'Exterior photography','drone':'Aerial photography','twilight':'Twilight photography'}[cat];alt=caption+' by ListerPros'
  items.append(f'<a class="portfolio-item mp-gallery-item" data-category="{cat}" data-caption="{caption}" href="{E(src)}" aria-label="View {caption.lower()}"><img src="{E(src)}" alt="{E(alt)}" width="1200" height="900" loading="lazy" decoding="async"><span>{cat.title()} <b aria-hidden="true">↗</b></span></a>')
 return f'''<section class="mp-hero mp-portfolio-hero"><div class="mp-wrap"><div class="mp-portfolio-heading"><div>{eyebrow('Real Arizona listings. ListerPros photography.')}<h1>Make your next listing<br><em>worth a closer look.</em></h1></div><div><p>See the spaces, details and surroundings our team brings into focus.</p><a class="mp-text-link" href="#gallery">Explore the gallery ↓</a></div></div><div class="mp-portfolio-mosaic">{img('portfolio/interior-1.jpg','A bright kitchen with natural wood cabinetry','',True)}{img('portfolio/twilight-1.jpg','Arizona home photographed at twilight','',True)}</div><p class="mp-fine mp-photo-note">Photography from the ListerPros portfolio. Select any gallery image to view it larger.</p></div></section>
 <section class="mp-section"><div class="mp-wrap"><div class="mp-section-heading">{eyebrow('What good listing media makes clear')}<h2>The home. The setting.<br>The reason to take a look.</h2></div><div class="mp-looking-grid"><article><span>01 / INTERIORS</span><h3>Let the space speak.</h3><p>Bright rooms, clear details and the features buyers want to see before they book a showing.</p><a href="#gallery" data-gallery-jump="interior">Explore interiors ↗</a></article><article><span>02 / DRONE</span><h3>Put the property in context.</h3><p>See the footprint, outdoor spaces and surroundings from a perspective a room photo cannot give.</p><a href="#gallery" data-gallery-jump="drone">Explore drone work ↗</a></article><article><span>03 / TWILIGHT</span><h3>Show a different mood.</h3><p>Evening light brings another dimension to a home’s exterior and outdoor living areas.</p><a href="#gallery" data-gallery-jump="twilight">Explore twilight work ↗</a></article></div></div></section>
 <section class="mp-section mp-soft" id="gallery"><div class="mp-wrap"><div class="mp-gallery-top"><div>{eyebrow('Find the view you want')}<h2>Explore our photography.</h2></div><span id="mp-gallery-count" aria-live="polite">{len(photos)} photographs</span></div><div class="mp-filters" role="group" aria-label="Photography type">{''.join(f'<button class="filter-btn" data-filter="{cat}" aria-pressed="{str(cat=="all").lower()}">{label}</button>' for cat,label in [('all','All work'),('interior','Interiors'),('exterior','Exteriors'),('drone','Drone'),('twilight','Twilight')])}</div><div class="mp-full-gallery" id="portfolio-grid">{''.join(items)}</div></div></section>
 <dialog id="lightbox" class="mp-lightbox" aria-labelledby="lightbox-caption"><button id="lightbox-close" aria-label="Close photograph">×</button><figure><img id="lightbox-img" alt=""><figcaption id="lightbox-caption"></figcaption></figure><div class="mp-lightbox-controls"><button id="lightbox-prev" aria-label="Previous photograph">←</button><span id="lightbox-counter" aria-live="polite"></span><button id="lightbox-next" aria-label="Next photograph">→</button></div></dialog>
 {closing('Like what you see?<br>Let’s photograph your next listing.','Explore photo, video and tour packages, then choose your appointment.','View packages','/pricing')}'''

def teams(source):
 form=source.select_one('#lp-team-form');form['class']=['mp-team-form'];card=f'<div class="mp-questionnaire" id="team-questionnaire">{eyebrow("Let’s build the right arrangement")}<h2>Tell us about your team.</h2><p>Exploring a media arrangement for your team or brokerage? Share a few details for Dominic to review. Fields marked * are required.</p>{str(form)}</div>'
 return f'''<section class="mp-hero mp-teams-hero"><div class="mp-wrap mp-split"><div>{eyebrow('Teams & brokerages')}<h1>One media partner.<br><em>A stronger presentation<br>across your listings.</em></h1><p class="mp-lead">Give your agents a consistent place to turn for listing media—and a local team they can reach when they need help.</p><div class="mp-actions">{button('Tell us about your team','#team-questionnaire')}{button('See our work','/portfolio',True)}</div><p class="mp-fine">Serving real estate teams and brokerages across Arizona.</p></div><div class="mp-team-visual">{img('portfolio/interior-1.jpg','Professional photography for an Arizona listing','',True)}<div class="mp-team-visual-note"><span>YOUR AGENTS. YOUR LISTINGS.</span><strong>A consistent first impression.</strong><p>Photos · video · drone · 3D tours</p></div></div></div></section>
 <section class="mp-section"><div class="mp-wrap"><div class="mp-section-heading">{eyebrow('Think beyond the next shoot')}<h2>Professional media<br>for your entire team.</h2><p>From professional photography to video, drone and 3D tours, give every agent in your brokerage or team an easy way to book the right media for every listing through one trusted partner.</p></div><div class="mp-looking-grid"><article><span>FOR YOUR AGENTS</span><h3>A familiar way to book.</h3><p>One place to explore services and available appointments, with people to contact when questions come up.</p></article><article><span>FOR YOUR LISTINGS</span><h3>A consistent media partner.</h3><p>Professional photography and a range of video, drone and tour services for different properties and marketing plans.</p></article><article><span>FOR YOUR BUSINESS</span><h3>A partnership built for your team.</h3><p>Share your team’s volume, needs and expectations so we can explore customized pricing and build a long-term media partnership that supports your agents and brokerage.</p></article></div></div></section>
 <section class="mp-section mp-soft"><div class="mp-wrap mp-team-conversation"><div>{eyebrow('What we will talk through')}<h2>Start with how<br>your team actually works.</h2><p>No two teams have the same mix of agents, listings and markets. Your answers give us a useful starting point.</p></div><ol class="mp-conversation-list"><li><strong>Your activity</strong><span>Agent count, average transactions and the listings you take each month.</span></li><li><strong>Your expectations</strong><span>The media your agents use today, where the gaps are and what consistent use could look like.</span></li><li><strong>Your fit</strong><span>Coverage, service needs and interest in a preferred or exclusive arrangement.</span></li></ol></div></section>
 <section class="mp-section"><div class="mp-wrap mp-presentation"><div>{eyebrow('Bring the conversation to your agents')}<h2>Help your team get more<br>from professional media.</h2></div><div><p>Interested in a presentation for your team or brokerage? Tell us what would be most valuable to your agents. Dominic, who handles our team and brokerage partnerships, will follow up to discuss your needs and coordinate a session with you.</p><a class="mp-button" href="#team-questionnaire" data-team-presentation>Ask about a presentation ↗</a></div></div></section>
 <section class="mp-section mp-soft"><div class="mp-wrap mp-questionnaire-layout"><aside>{eyebrow('A conversation, not a commitment')}<h2>Let’s see what<br>we can build together.</h2><p>Team and brokerage inquiries go to Dominic. He’ll review your answers and contact you about next steps. Pricing, service expectations and any commitment would be discussed separately.</p><div class="mp-contact-card"><strong>Here for your own listings?</strong><p>Our admin team can help with booking, services and questions about your media. Start here; they can arrange specialist advice if needed.</p><a href="tel:4805827767">480.582.7767</a><a href="mailto:info@listerpros.com">info@listerpros.com</a></div><a class="mp-text-link" href="/pricing">View standard packages ↗</a></aside>{card}</div></section>'''

def resources(source):
 # Curated starting points; the full existing library remains one click away.
 guides=[('playbook','launch','Listing Launch Playbook','Plan the first week of a listing.','playbook-hub-cover.jpg'),('open-house-playbook','launch','Open House Playbook','Prepare, promote and follow up.','open-house-playbook'),('listing-presentation-playbook','win','Listing Presentation Playbook','Prepare for your next seller conversation.','listing-presentation-playbook'),('geographic-farm-playbook','grow','Geographic Farm Playbook','Build a plan for the area you serve.','geographic-farm-playbook'),('video-starter-playbook','grow','Video Starter Playbook','Get started with video for your business.','video-starter-playbook'),('referral-playbook','grow','Referral Playbook','Build a more intentional referral habit.','referral-playbook'),('buyer-consult-playbook','clients','Buyer Consultation Playbook','Prepare for a productive buyer conversation.','buyer-consult-playbook'),('seller-update-playbook','clients','Seller Update Playbook','Keep sellers informed as a listing progresses.','seller-update-playbook')]
 catalog=soup((ROOT/'live/guides.html').read_text());cards=[]
 for slug,category,title,description,fallback in guides:
  a=catalog.select_one(f'a[href="/{slug}"]')
  if not a:a=next((x for x in catalog.select('a[href]') if slug in x['href']),None)
  cover=a.img['src'] if a and a.img else 'images/guides/playbook-hub-cover.jpg';cover='/'+cover.lstrip('/')
  cards.append(f'<a class="mp-guide-card" data-resource-category="{category}" href="/{slug}"><div class="mp-guide-cover"><img src="{E(cover)}" alt="{E(title)} cover" width="600" height="450" loading="lazy"><span>Free guide</span></div><div><h3>{title}</h3><p>{description}</p><span class="mp-guide-open">Open guide ↗</span></div></a>')
 form=source.select_one('#guide-request-form');form['class']=['mp-resource-request']
 for field,label in [('note','What would you like help with?'),('email','Your email')]:
  el=form.select_one(f'[name="{field}"]');el['id']='mp-request-'+field;lab=source.new_tag('label',attrs={'for':el['id']});lab.string=label;el.insert_before(lab)
 return f'''<section class="mp-hero mp-resources-hero"><div class="mp-wrap mp-split"><div>{eyebrow('Free resources for Arizona agents')}<h1>A little less searching.<br><em>A useful next step.</em></h1><p class="mp-lead">Find neighborhood photos, get your seller ready for photo day, or build a plan for your next listing. Start with the job in front of you.</p><a class="mp-button" href="#resource-guides">Find a guide ↓</a></div><div class="mp-quick-resources"><a href="/community-photos/">{img('community/community-012.jpg','Arizona community amenities')}<div><span>SHOW THE NEIGHBORHOOD</span><h2>Community photos</h2><p>Explore the Arizona archive.</p><b aria-hidden="true">↗</b></div></a><a href="/shoot-prep"><div class="mp-prep-mark" aria-hidden="true">✓</div><div><span>BE READY FOR PHOTO DAY</span><h2>The shoot prep checklist</h2><p>A practical page to send your seller.</p><b aria-hidden="true">↗</b></div></a></div></div></section>
 <section class="mp-section" id="resource-guides"><div class="mp-wrap"><div class="mp-gallery-top"><div>{eyebrow('Pick what you are working on')}<h2>A guide for your next move.</h2></div><a class="mp-text-link" href="/guides">See all 23 free guides ↗</a></div><div class="mp-filters" role="group" aria-label="Resource goal">{''.join(f'<button data-resource-filter="{cat}" aria-pressed="{str(cat=="all").lower()}">{label}</button>' for cat,label in [('all','All starting points'),('launch','Launch a listing'),('win','Win a listing'),('grow','Grow my business'),('clients','Support my clients')])}</div><p class="mp-resource-status" id="mp-resource-status" aria-live="polite">8 selected starting points</p><div class="mp-guide-grid">{''.join(cards)}</div></div></section>
 <section class="mp-section mp-soft"><div class="mp-wrap mp-resource-next"><div>{eyebrow('Keep learning, or get an answer')}<h2>The right place<br>for the next question.</h2></div><a href="/blog/"><span>THE BLOG</span><h3>Explore ideas for your market.</h3><p>More articles on listing media, preparation and real estate marketing.</p><b>Read the blog ↗</b></a><a href="/help-center"><span>HELP CENTER</span><h3>Get the practical details.</h3><p>Ordering, delivery, service options and answers to common questions.</p><b>Find an answer ↗</b></a></div></section>
 <section class="mp-section"><div class="mp-wrap mp-split mp-request-layout"><div>{eyebrow('Tell us what would help')}<h2>Missing the guide<br>you wish existed?</h2><p>Suggest a topic for a future guide. Agent requests help us decide what to make next.</p><a class="mp-text-link" href="/newsletter">Explore the Elite Agent newsletter ↗</a></div><div class="mp-request-panel">{str(form)}</div></div></section>'''

BUILDERS={'why.html':lambda s:why(),'pricing.html':pricing,'portfolio.html':portfolio,'teams.html':teams,'resources.html':resources}
def render(path,text):
 if path not in PAGES:return text
 source=soup(text);content=BUILDERS[path](source)
 titles={'why.html':'Why ListerPros | A Local Team for Your Next Listing','pricing.html':'Real Estate Media Packages & Pricing | ListerPros','portfolio.html':'Arizona Real Estate Photography Portfolio | ListerPros','teams.html':'Media for Arizona Teams & Brokerages | ListerPros','resources.html':'Free Resources for Arizona Real Estate Agents | ListerPros'}
 descriptions={'why.html':'Professional listing media, clear communication and an experienced Arizona team. See why real estate agents try ListerPros and keep coming back.','pricing.html':'Compare ListerPros photo, video and 3D packages by property size. Explore inclusions and add-ons, then review your final price and appointment during booking.','portfolio.html':'Explore real Arizona listing photography by ListerPros: interiors, exteriors, drone and twilight images. Browse the gallery and find a package for your next listing.','teams.html':'Explore a real estate media partnership for your Arizona team or brokerage. Share your volume, media needs and interest in a team presentation.','resources.html':'Find free Arizona community photos, a seller shoot-prep checklist and practical guides for launching listings, serving clients and growing your real estate business.'}
 for meta in source.select('meta[name="description"],meta[property="og:description"],meta[name="twitter:description"]'):meta['content']=descriptions[path]
 for style in source.head.select('style'):style.decompose()
 if source.title:source.title.string=titles[path]
 for meta in source.select('meta[property="og:title"]'):meta['content']=titles[path]
 scripts=[]
 for sc in source.body.select('script'):
  code=sc.get_text()
  if path=='portfolio.html' and 'filterButtons' in code:continue
  scripts.append(str(sc))
 return '<!doctype html><html lang="en">'+str(source.head)+'<body class="lp-menu-page" data-lp-menu-refresh="true"><main>'+content+'</main>'+''.join(scripts)+'</body></html>'
